name: Test & Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        coverage run manage.py test

    - name: Generate coverage report
      run: coverage report

    - name: Coverage in XML format to display
      run: coverage xml

    - name: Display coverage report
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          const xmlReport = fs.readFileSync('./coverage.xml', 'utf8');
          console.log(xmlReport);
